---
title: "p8105_finalproject"
author: "TritonD"
date: "11/5/2019"
output: github_document
---

# P8105 Final Project Proposal 

**The group members (names and UNIs)**
Xingyuan Chen (xc2473);  Xin He (xh2395); Yunzhi Qian (yq2251); Stephanie Zhen (sz2800); Katie Gao (kxg2002)

**The tentative project title**
H1-B Visa Application Characteristics in America

**The motivation for this project**
As immigration policies are changing in the US. Many international students are concerned about their eligibility to work in the states. As international students and friends of international students who are able to graduate, we are interested in how H1B visa applications will affect/dictate our job-seeking opportunities. We have multiple group members who are personally interested in this topic. 

**The intended final products**
Comparisons of the number of Visa applicants by states, years, industries (SOC code/SOC name) and nationalities
Wage distribution of Visa applicants
The average length for process period for the Visa application

**The anticipated data sources**
https://public.enigma.com/datasets/h-1-b-visa-applications-2018/51d8447d-7e47-4334-8373-610ee46b69e6?filter=%2B%5B%3Eemployer_state%5BCA%5D%5D



